### PR TITLE
Collab: Support smart undo/redo

### PR DESCRIPTION
**Pull request by mirka**
## Proposed changes

This enables undo/redo functionality, which was previously disabled when collaborative editing.

The crux of multiplayer undo is that the "origin" of each change is tracked, so that each player is only undoing their own changes and not others. Yjs provides an [Undo Manager](https://docs.yjs.dev/api/undo-manager) module to handle origin-aware undo stacks.

Integrating this module required some changes to the data flow, but on the whole I think those changes are good. Data flow is now more simplified, and I took this opportunity to rename some things for better readability. Our main integration point is now in [redux middleware](https://github.com/Automattic/isolated-block-editor/pull/68/files#diff-d25fdb9e07d6c3ef1c2e7eec87cdac83dff057ed66a05750b94d7512ca385c77) — for both blocks state updates and undo actions. These will all safely no-op when collab is not enabled or initialized.

✅ UI integration tests pass (single player and multiplayer undo)

### TODO before merging

- [x] Bundle files
- [x] Add changelog entry (⚠️ selector names were changed)

## To test

1. `yarn storybook` and open the collab editor story in two browser windows.
2. Single player undo should work as expected.
3. Multiplayer undo should work intuitively, _as long as they are editing separate blocks_. (Single paragraph concurrent edits aren't fully supported yet — #71)

The base case for multiplayer undo is like this:

1. User A types in the first paragraph.
2. User B types in the second paragraph.
3. User A triggers an undo. Their own changes in the first paragraph should be reverted, but not User B's changes in the second paragraph.
4. User B triggers an undo. Their own changes in the second paragraph should be reverted.

### CODE REVIEW

**Comment by johngodley** [comment]
> yarn storybook and open the collab editor story in two browser windows.

Sorry, can you remind me how to get this working in storybook? When I try it it loads the storybook with some options, but I don't see a way to actually run it. I'm probably missing something very easy!

> if you want you can test the changes on a sandboxed P2 

The patch failed for me so I guess there have been some changes to trunk since.

**Review by lamosty — APPROVED** [review]
Super great work @mirka!

I've tested it in the Storybook and reviewed the code and it all looks fine. The tests are really nice, wow.

I'm wondering: does it make sense to add some block modifications to the tests as well? Like making the text bold. I know it shouldn't really matter to the yjs undo manager, so your call.

**Comment by johngodley** [comment]
@lamosty helped me out - for me Storybook keeps defaulting to showing a wide settings panel that hides the editor.

It tested out as described above, and the no-collab editor undo works as normal too. The code looks great.

There seems to be some strange edge cases when both peers add a block. This may be part of your caveat `as long as they are editing separate blocks` as I think the process of adding a block may cross this boundary, and it may be caused by #89, but I'll mention it just in case:

- Open 2 tabs, type in one
- Add block to second (block inserter, add paragraph), type in block
- In first peer, undo a few times. Both blocks are removed. Redo to add the blocks back
- Second peer can no longer undo the block they added

**Comment by mirka** [comment]
Thanks for the reviews & testing! 🙏 

> I'm wondering: does it make sense to add some block modifications to the tests as well? Like making the text bold. I know it shouldn't really matter to the yjs undo manager, so your call.

@lamosty Good one. You're right that the undo manager does not care, but testing formatting will become very relevant after #71 where format edits become less straightforward in Yjs. I'll definitely keep that in mind.

> I think the process of adding a block may cross this boundary

@johngodley Argh I can totally see how that could potentially happen, but somehow I can't trigger it. Am I doing it correctly? Were you able to reproduce it consistently?

https://user-images.githubusercontent.com/555336/144040384-a812220d-5f0e-4e6d-876d-5ee7cb529411.mp4

In contrast, this is the main "cross-boundary" case that is expected to happen — when User B types in an empty paragraph that User A added:

https://user-images.githubusercontent.com/555336/144041591-538452c6-873b-4e65-8e07-4d323bf5ebe2.mp4

I'm trying to determine if you're seeing legitimate cross-boundary issues (which we can't do much about in this PR), or if it's something different.

**Pull request merged**
