### PR TITLE
Update @wordpress/scripts

### LINKED ISSUE #127: Update @wordpress/scripts to ^22.4.0
Updating this results in a `yarn test` error:

```
FakeTimers: clearTimeout was invoked to clear a native timer instead of one created by this library.
To automatically clean-up native timers, use `shouldClearNativeTimers`.
```

Followed by a couple of failed tests:

`expect( screen.getByRole( 'document', { name: 'Paragraph block' } ) ).toHaveTextContent( 'hello' );`

### PR DESCRIPTION
**Pull request by johngodley**

### CODE REVIEW

**Comment by johngodley** [comment]
@mirka do the Yjs unit test errors look familiar to you? It seems like some of the Gutenberg HTML has changed. I tried digging in a bit, but just managed to move the problem further down.

**Comment by mirka** [comment]
> do the Yjs unit test errors look familiar to you?

Not immediately, no. I'll see if I can take a look tomorrow, or if not, next Tuesday.

**Comment by mirka** [comment]
Production (not devDeps) dep issues were addressed in #110. This PR is now rebased and only bumps `@wordpress/scripts`. (I dropped the explicit dependency on `@wordpress/jest-preset-default` — let me know if you added that for a reason.)

**Review by mirka — APPROVED** [review]
Good to go on my end, merge at will! 🚢

**Comment by johngodley** [comment]
This was handled as part of #144 so closing this one.

**Pull request closed without merging**
