### PR TITLE
Add .nvmrc for node 14

### PR DESCRIPTION
**Pull request by westonruter**
I tried `npm install` with node 16 but it failed with:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @automattic/isolated-block-editor@2.14.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-autosize-textarea@7.1.0
npm ERR! node_modules/react-autosize-textarea
npm ERR!   react-autosize-textarea@"^7.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

When switching to node 14 the installation succeeded. 

Since Gutenberg still has an `.nvmrc` with `14`, this seems necessary for this repo as well.

### CODE REVIEW

**Comment by mirka** [comment]
Great, thanks! Let's also update the `engines` in package.json with an upper bound. Or maybe we should just match the [one in Gutenberg](https://github.com/WordPress/gutenberg/blob/d3157c73eaf85455021712839b261975a7f9dc7a/package.json#L18). Any preferences here? @johngodley @msurdi

**Comment by johngodley** [comment]
Yeah, we should match Gutenberg's node version. I'll update that soon.

Thanks for the PR!

**Comment by westonruter** [comment]
While the change here let me `npm install`, when running `npm run build:browser` I got an error:

```
ERROR in isolated-block-editor.js from Terser
Unexpected token: punc (.) [isolated-block-editor.js:258548,15]
```

**Comment by johngodley** [comment]
I've not seen that one, and it sounds like another version incompatibility somewhere. I'll investigate.

**Comment by johngodley** [comment]
The project is using `yarn` so you may find things work better with that.

I've tried with `npm` and it seems to work ok for me using node `14.19.0` and npm `8.5.2`

**Pull request merged**
